---
title: "iNeedADrink - Routing and Controllers"
type: "challenge"
description: "Make controller and routing related changes to fix a broken application"
visibility: "assign"
tags: "rails, routing, controllers"
ignore:
  - "iNeedADrink-routing.md"
